---
driver:
  name: docker
  use_sudo: false
  privileged: true
  hostname: salt-formula.ci.local
  require_chef_omnibus: false  

platforms:
  - name: ubuntu-18.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales ifupdown
        - locale-gen en_US.UTF-8
        - update-locale LANG=en_US.UTF-8
        - mkdir -p /run/sshd
      run_command: /lib/systemd/systemd
  - name: debian-9
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales ifupdown
        - locale-gen en_US.UTF-8
      run_command: /lib/systemd/systemd
  - name: centos-7
#   driver_config:
#     run_command: /lib/systemd/systemd

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_pillar_root: pillar.example
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: tomcat
  state_top:
    base:
      '*':
        - tomcat
suites:
  - name: tomcat_install
    provisioner:
      state_top:
        base:
          '*':
            - tomcat
            - tomcat.native
            - tomcat.config

  - name: tomcat_extend
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.manager
            - tomcat.vhosts
            - tomcat.expires
            - tomcat.context
            - tomcat.cluster
